#!/usr/bin/env python
from subprocess import check_output
import requests
import os
import json
log = check_output(['git', 'log', '-1', '--pretty=%B'])
reflog = check_output(['git', 'reflog', '-1'])
print reflog
dirpath = os.path.dirname(os.path.abspath(__file__))
pw = open(dirpath+'/creds').read().strip()
resp = requests.get(
    'https://projects.databrary.org/jira/rest/api/2/search?jql=assignee%3Dmaksim.levental&fields=summary%2Ccreator',
    auth=('maksim.levental', pw)
).json()
my_issues = filter(lambda x: x['fields']['creator']['key'] == 'maksim.levental', resp['issues'])
summaries = {x['fields']['summary']: x['id'] for x in my_issues}
current_branch = ' '.join(check_output(['git', 'rev-parse', '--abbrev-ref', 'HEAD']).strip().split('_')).title()
branch_id = summaries[current_branch]

comment = '{"body": "%s"}' % log.strip()

resp = requests.post('https://projects.databrary.org/jira/rest/api/2/issue/{}/comment'.format(branch_id), json=json.loads(comment),
                     auth=('maksim.levental', pw))

comment = '{"transition": {"id": "31"}}'  # 41 is the done transition

print resp.status_code

resp = requests.post('https://projects.databrary.org/jira/rest/api/2/issue/{}/transitions'.format(branch_id),
                     json=json.loads(comment),
                     auth=('maksim.levental', pw))

print resp.status_code